controller/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "products#index"
  root "products#index"
  # root "admins#index"

  # Defines the root path route ("/")
  # root "articles#index"
  resources :products, :admin, :users
  get "admin", to: "admin#admin"
  # resource :admin, :controller => "admin"

  # resources :admin
end

controller/app/models/admin.rb
class Admin < ApplicationRecord
  # belongs_to :user
  # has_many :products, through: :users
end

controller/app/models/product.rb
class Product < ApplicationRecord
  # belongs_to :user
  # scope :search, ->(search) { where("name like ?", "#{search}%") }

  def self.search(search)
    products = where("name like ?", "#{search}%")
    products.present? ? products : all
  end
end

controller/app/models/user.rb
class User < ApplicationRecord
  # has_many :products
  # has_many :admins
end

controller/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin, except: [:index]
  # before_action :require_admin

  def admin
  end

  def index
  end

  private

  def require_admin
    unless current_user.isAdmin?
      redirect_to root_path
    end
  end
end

controller/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    @current_user = User.last
  end
end

controller/app/controllers/products_controller.rb
class ProductsController < AdminController
  # before_action :require_admin, only: [:new, :create, :destroy]
  skip_before_action :require_admin, only: [:index]

  def index
    @products = Product.search(params[:search])
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :color, :company_name, :rating, :price, :search)
  end
end

controller/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :verify_authenticity_token

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_path(user_id: @user.id)
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :isAdmin)
  end
end

controller/app/helpers/admin_helper.rb
module AdminHelper
end

controller/app/helpers/products_helper.rb
module ProductsHelper
end

controller/app/helpers/users_helper.rb
module UsersHelper
end

controller/app/views/admin/admin.html.erb
<p>Admin page</p>

controller/app/views/admin/index.html.erb
<p>Admin Page</p>

<%= link_to "New Product", new_product_path %>

controller/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controller</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

controller/app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
    <% user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
  <div>
    <%= form.check_box :isAdmin %>
    <label for="isAdmin"> <%= t "is admin" %> </label>
  </div>
    <% user.errors.full_messages_for(:isAdmin).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

controller/app/views/users/index.html.erb
<h1>All User List</h1>
<% @users.each do |user| %>
  <li>
      <a href="<%= user_path(user) %>">
      <%= user.name %>
    </a>
  </li>
  <% end %>

<%= link_to "New user", new_user_path %>

controller/app/views/users/new.html.erb
<h1>New User</h1>
<%= render "form", user: @user %> 

controller/app/views/users/show.html.erb
<p><%= @user.name %></p>
<p><%= @user.email %></p>
<p><%= @user.isAdmin %></p>

<li>
  <%= link_to "Destroy", user_path(@user), data: { turbo_method: :delete } %>
</li>